targetGroupId: -1002280787740
helloMessage: >-
  Приветствую🤙 Ты можешь сюда что-то прислать, например идею или смешной мем, и твоё сообщение поступит владельцу бота🤖.
bannedMessage: Вы заблокированы и не можете писать в предложку👎.
timeoutMessage: Писать можно раз в 10 секунд! Подождите и попробуйте снова.
successEmoji: 👌
banList:
  - 12
  - .nan
trustedUsers:
  - 1347012166
  - 5376829237
  - 1345091383
  - 5194914734