token: 7677724353:AAGsFoFr_HCRCHCytB9st3L21QCD5Nkr6j4
targetGroupId: -1002280787740
helloMessage: >-
  Привет! Ты можешь сюда что-то прислать, например идею или смешной мем, и оно
  перешлётся владельцу бота.
bannedMessage: Вы заблокированы и не можете писать в предложку.
timeoutMessage: Писать можно раз в 3 секунды! Подождите и попробуйте снова.
successEmoji: 👌
banList:
  - null
trustedUsers:
  - 1347012166
  - 5376829237
  - 1345091383