targetGroupId: -1002280787740
helloMessage: >-
  Приветствую🤙 Ты можешь сюда что-то прислать, например идею или смешной мем, и твоё сообщение поступит владельцу бота.
bannedMessage: Вы заблокированы и не можете писать в предложку👎.
timeoutMessage: Писать можно раз в 10 секунд! Подождите и попробуйте снова.
weekLimitMessage: Был достигнут лимит в 1000 сообщений в неделю! Этот лимит существует, чтобы не перегружать бота. Вы можете подождать до сброса лимита
successEmoji: 👌
banList: [1]
trustedUsers:
  - 1347012166
  - 5376829237
  - 1345091383
  - 5194914734
proposioToken: 7577899392:AAGYkOzhjQ2s9_0keENE2xdlz-UaKFj3ohw